### ISSUE TITLE
Ajax uploader doesn't complete - just a PW 3.x problem?

### ISSUE THREAD

**Issue by adrianbj** [justonestep/processwire-imageextra#16] opened 2016-05-17 22:42 UTC
I think this is new to PW 3.x

The file (in this case a PDF in a FieldtypeFile) actually does get uploaded, but the ajax uploader never finishes.

I am not sure why the module is even touching this field because in the module settings I have only selected: InputfieldImage

I made a couple of quick hacks to get things working.

around line: 656

```
$p = $event->object->value['page'];

/added this line - without this, the pdf won't upload to the file field. $p is being returned as false
if(!$p) return;
   
 $image = $event->argumentsByName("pagefile");
```

around line: 693
```
    $fieldName = $value->field->name;

    // added this line to prevent a warning about undefined index of the name of the field
    if(!isset($this->additionalFields['other'][$fieldName])) return; 
    
$combine = $this->additionalFields['other'][$fieldName];
```

These changes seem to get things working again, but I do think some proper detection to prevent hooks being added to undesired fields needs to be implemented.

Thanks!

**Comment by justonestep** [comment] 2016-05-30 08:39
Hi, which version of the module do you use? For PW3.x compatibility the module needed some changes which are currently in develop branch. And in this new version I removed the module setting to select a FieldType. So the module checks if **image extra fields** are checked in field settings, otherwise it does nothing. I tested it with a fresh PW3.18 installation and can't reproduce the behaviour you described.

**Comment by justonestep** [comment] 2016-05-30 10:06
I'll close this for now. If you still have any trouble, feel free to reopen this issue.

**Closed by justonestep** 2016-05-30 10:06 UTC

**Comment by Pauldro** [comment] 2016-11-15 23:07
@adrianbj Can you upload your version of the ImageExtra.module, I'm running into the same issue, and I tried adding those lines but I'm not sure I am sticking them in the right place. Thanks in advance.

**Comment by adrianbj** [comment] 2016-11-15 23:21
@Pauldro - have you tried the https://github.com/justb3a/processwire-imageextra/tree/develop branch of this module? I think that is what I am currently using without problems. If that doesn't work for you, I'll take a look and see if I am still making use of that hack and post for you.

**Comment by Pauldro** [comment] 2016-11-16 15:45
@adrianbj I looked at that module, it didn't work however I did manage to use your hack in it, however I may have put it in a different place you did 

I put it in the function `function processInputAddFileExtra(HookEvent $event) `
After the line 
`if ($maxFiles > 1 && $total >= $maxFiles) return;`
I used the lines you suggested : 
`$p = $event->object->value['page'];
    //added this line - without this, the pdf won't upload to the file field. $p is being returned as false
    if(!$p) return;`

Either way, thanks a lot Adrian for pointing my nose in the right direction!
